/**
 * Placeholder until synaptik publish. Regenerated by Synaptik — do not edit manually after publish.
 */
export const projectSlug = 'my-product' as const;

export const iconsBySlug = {} as const;

export type GeneratedIconSlug = keyof typeof iconsBySlug;

export function getGeneratedIcon(slug: GeneratedIconSlug) {
  return iconsBySlug[slug];
}
